export const personelChanceData = [
    {
        "Sicil No": "3190",
        "Personel": "MEHMET ALİ BACAK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "0",
        "newScore": "1"
    },
    {
        "Sicil No": "1725",
        "Personel": "AHMET KOCABAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "1659",
        "Personel": "DERYA GÜLDÜ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0283",
        "Personel": "REŞAN YOLCU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0360",
        "Personel": "NURAN KESİK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "3129",
        "Personel": "CÜNEYT YILDIRIM",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "3021",
        "Personel": "CİHAN BEDİR",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "2827",
        "Personel": "ERDOĞAN ERYILMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "2833",
        "Personel": "ALİ TÜRKOĞLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Kalite Ayrım İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SONGÜL KARABUĞA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "3071",
        "Personel": "YASİN ANIL KAYNARCA",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "2559",
        "Personel": "ÜMİT ERDOĞAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Veri Giriş  Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SONGÜL KARABUĞA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "1277",
        "Personel": "BEKİR SARI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Bakım ve Enerji",
        "Görev": "Bakım ve Enerji Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "EREN ÇAĞLAR",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "1931",
        "Personel": "AYŞE AY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "TOLGA SOY",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "1804",
        "Personel": "MUSTAFA KOLTUK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CEREN DEMİR",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0543",
        "Personel": "HABİL EFE",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Bakım ve Enerji",
        "Görev": "Bakım ve Enerji Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "EREN ÇAĞLAR",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0288",
        "Personel": "ÖZLEM GÜVEN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "TOLGA SOY",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0275",
        "Personel": "SANİYE TAŞ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "TOLGA SOY",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "1669",
        "Personel": "SEVDA DİNLEYEN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Kalite Ayrım İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SONGÜL KARABUĞA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0702",
        "Personel": "ÖMÜR DENİZLİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Fırınlar",
        "Görev": "Bisküvi Pişirim  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "HALİL ERHAN KILIÇ",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "0286",
        "Personel": "RAHİLE UYKUN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "1",
        "newScore": "1"
    },
    {
        "Sicil No": "2953",
        "Personel": "CANSU ÇATAK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2957",
        "Personel": "FATMA BAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "3048",
        "Personel": "YASİN ÇAY",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1737",
        "Personel": "TUNAHAN TATAR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Koli Depo Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "ÖZGE DEMİRKAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1155",
        "Personel": "DOĞUKAN DEMİR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "0442",
        "Personel": "NAİM ORAL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2897",
        "Personel": "BERAT DEMİRYÜREK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2894",
        "Personel": "SALİH AYKOL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "3035",
        "Personel": "BÜŞRA ÇAKICI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "3104",
        "Personel": "ÖZLEM KARAMAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2816",
        "Personel": "TANJU KARA",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2771",
        "Personel": "ÇİLEM TİKAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2607",
        "Personel": "ALİ ARSLAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2120",
        "Personel": "HASAN ÖZBİÇER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2152",
        "Personel": "FAHRİYE YILDIZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2270",
        "Personel": "AYSEL ER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2134",
        "Personel": "RASET CEVİZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1470",
        "Personel": "CAN TEKİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1596",
        "Personel": "SERDAR AYDI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1678",
        "Personel": "YAKUP TİMUÇİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1786",
        "Personel": "MEMET ULU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1408",
        "Personel": "BÜKRENUR YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1649",
        "Personel": "SEHER YILDIZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1943",
        "Personel": "ECE BURÇİN YILDIZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1710",
        "Personel": "RABİA GÜÇLÜ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "1721",
        "Personel": "FADİME YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "2",
        "newScore": "46"
    },
    {
        "Sicil No": "2742",
        "Personel": "NİDA NUR SAVAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2845",
        "Personel": "BAYRAM KARAOĞLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Elektrik",
        "Görev": "Elektrik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3095",
        "Personel": "NURGÜL SÖNMEZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3034",
        "Personel": "İSMAİL ÖZEN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Sırlı Fırın Boşaltma İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3169",
        "Personel": "APTULLAH LAMA",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3124",
        "Personel": "ŞÜKRAN KAYALI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "ÖZGE SÜRGİT",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3137",
        "Personel": "FESİME UNUTMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2846",
        "Personel": "HÜSEYİN KARADAYI",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Elektrik",
        "Görev": "Elektrik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2898",
        "Personel": "SEZGİN KURUOĞLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Elektrik",
        "Görev": "Elektrik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3119",
        "Personel": "SEYDİHAN YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2688",
        "Personel": "ALİCAN SEZGİN YAPICI",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "Proses Kontrol",
        "Görev": "Proses Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2873",
        "Personel": "ÖNDER ATASOY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Elektrik",
        "Görev": "Elektrik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2823",
        "Personel": "SERDAR TOSUN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "Proses Kontrol",
        "Görev": "Proses Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2789",
        "Personel": "MURAT CEYLAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2792",
        "Personel": "ADNAN KİRAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Model/Teksir",
        "Görev": "Model/Teksir  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2808",
        "Personel": "NİHAT KAYA",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2273",
        "Personel": "İLAYDA HEKİM",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2672",
        "Personel": "HASAN DURMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2580",
        "Personel": "RECEP BAYRAM BİBER",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Metot/Opex",
        "Bölüm": "Metot",
        "Görev": "Metot Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "GÖRKEM DÖRTKÖŞE",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2556",
        "Personel": "SİNEM GÜNDÜZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "Proses Kontrol",
        "Görev": "Proses Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2597",
        "Personel": "BURCU KETECİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1432",
        "Personel": "EMEL ARI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1598",
        "Personel": "DADAŞ KAHRAMAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Sırlı Fırın Boşaltma İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1543",
        "Personel": "SEVGİ ÇEVİK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "Proses Kontrol",
        "Görev": "Proses Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0847",
        "Personel": "ERGÜL SATIR",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0505",
        "Personel": "MEHMET SARIHAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0502",
        "Personel": "SERPİL KAHRAMAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Son Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0843",
        "Personel": "AYDAN TOPALOĞLU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Numune Depo",
        "Görev": "Numune Depo Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0850",
        "Personel": "MELİSA KOPUK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Veri Giriş  Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0851",
        "Personel": "MURAT TOPALOĞLU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0500",
        "Personel": "SELMİN İPEK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0339",
        "Personel": "İSHAK ÜMSÜR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "ÖZGE DEMİRKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0041",
        "Personel": "AYKUT BAY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0010",
        "Personel": "ADEM ÖZKAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Mekanik",
        "Görev": "Mekanik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0082",
        "Personel": "CENGİZ ZENCİRCİ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0084",
        "Personel": "COŞKUN ŞAHİN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0253",
        "Personel": "SONA AKÇAY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe  Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0337",
        "Personel": "HATUN CAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2967",
        "Personel": "HÜSEYİN EREN BEKTAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2925",
        "Personel": "ÖZKAN ERDAĞLI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2921",
        "Personel": "IRMAK POYRAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3103",
        "Personel": "MUSTAFA ÇETİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3144",
        "Personel": "SEMİH FİDAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2923",
        "Personel": "EBRU KILIÇARSLAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3023",
        "Personel": "ALİ TUNCER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2874",
        "Personel": "GONCA GAZAİOĞLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2936",
        "Personel": "OĞUZHAN BALLI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3100",
        "Personel": "SEYHAN YEGÜL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2980",
        "Personel": "KADİR KESKİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3098",
        "Personel": "HALİME AYDOĞAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2844",
        "Personel": "ARİF SAKAL",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Şoför NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖZGE DEMİRKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2837",
        "Personel": "SEVGİ OLGUNSOY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3173",
        "Personel": "ERGİN AYDIN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2775",
        "Personel": "BÜLENT KESKİN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "TOLGA SOY",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3177",
        "Personel": "ÜMMÜ GÜLSÜM KORKMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2852",
        "Personel": "BARIŞ TUNÇER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Vardiya Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2900",
        "Personel": "HACER DEMİRTAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3012",
        "Personel": "KEREMCAN BAL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3161",
        "Personel": "AHMET KOÇAK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3178",
        "Personel": "SEVDA YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2787",
        "Personel": "NURDAN ÖZTÜFEKCİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Veri Giriş Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2349",
        "Personel": "İSMAİL ÜNVER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2363",
        "Personel": "SERKAN BERBER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2007",
        "Personel": "ÖZCAN VURAL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Bakım ve Enerji",
        "Görev": "Bakım ve Enerji Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "EREN ÇAĞLAR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2197",
        "Personel": "DAMLA DEMİRAL",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CEREN DEMİR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2321",
        "Personel": "UFUK OKAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Bakım ve Enerji",
        "Görev": "Bakım ve Enerji Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "EREN ÇAĞLAR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2555",
        "Personel": "MERCAN BAYANER",
        "Çalışma Yeri": "Pendik",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "GÖKHAN SUBAŞI",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2682",
        "Personel": "HATİCE TUNÇAY",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1295",
        "Personel": "ÖMER ÖZBEY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CEREN DEMİR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1887",
        "Personel": "SALİM ŞAHİN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Mal Kabul",
        "Görev": "Mal Kabul Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "ÖZGE DEMİRKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1284",
        "Personel": "YAREN BERİVAN SARIAYDIN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Veri Giriş Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "BURHAN GÖL",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1807",
        "Personel": "HASAN BAYRAM",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1150",
        "Personel": "AHMET KÜÇÜK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1469",
        "Personel": "KAAN AKKERMAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1386",
        "Personel": "AZİZ BULUT",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1739",
        "Personel": "ZAFER BAYINDIR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Teknik Depo",
        "Görev": "Teknik Depo Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0984",
        "Personel": "GAMZE YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0849",
        "Personel": "LEYLA GÜRGEN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Son Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1064",
        "Personel": "HÜSEYİN KAYA",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Forklift",
        "Görev": "Forklift Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "ÖZGE DEMİRKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0900",
        "Personel": "ÇETİN FARUK ÖZER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "Temizlik Eleman  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0558",
        "Personel": "KEVSER ÇEVİK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Veri İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0381",
        "Personel": "OSMAN DEMİR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "TOLGA SOY",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0390",
        "Personel": "YASEMİN BOZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CEREN DEMİR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0375",
        "Personel": "ŞUAYİP CANKAL",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0245",
        "Personel": "ŞENAY BÜTÜN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0086",
        "Personel": "ZÜLEYHA ŞARLAK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "CEREN DEMİR",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0160",
        "Personel": "GONCAGÜL EROL",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0040",
        "Personel": "AYFER ORHAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0326",
        "Personel": "GÖKHAN AKKAYA",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "İSMAİL TANRIVERDİ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3131",
        "Personel": "AYBERK FERAH",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Fırınlar",
        "Görev": "Bisküvi Stok İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "HALİL ERHAN KILIÇ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1947",
        "Personel": "RECEP DUMAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0440",
        "Personel": "MURAT ŞAHİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Fırınlar",
        "Görev": "Bisküvi Pişirim Fırınlar Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "HALİL ERHAN KILIÇ",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0472",
        "Personel": "İSMAİL ERDİNÇ TAŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0473",
        "Personel": "İSMAİL TEKİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2801",
        "Personel": "AYHAN ÜNAL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2794",
        "Personel": "MUSTAFA BALTA",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2750",
        "Personel": "ENGİN CAN AKÇA",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlı Fırın Yükleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2490",
        "Personel": "ÖZKAN MUTLU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Robot Pres Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "2475",
        "Personel": "KENAN SEVİMLİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Robot Pres Lider Operatör  NW",
        "Organizasyon yeri": "LOPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1244",
        "Personel": "MURAT ÇELİK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1421",
        "Personel": "ONUR TEKİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Robot Pres Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "1396",
        "Personel": "MURAT MERCAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Kalıp Bakım  Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0808",
        "Personel": "HACER DİLEK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Robot Pres Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0511",
        "Personel": "YALÇIN YILMAZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0477",
        "Personel": "VEDAT ÇAM",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "0428",
        "Personel": "ENVER KURT",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Şekillendirme",
        "Görev": "Şekillendirme Presler  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CENGİZ KAYA",
        "newScala": "3",
        "newScore": "61"
    },
    {
        "Sicil No": "3117",
        "Personel": "BARBAROS MERT İPŞİR",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Metot/Opex",
        "Bölüm": "Metot",
        "Görev": "Metot Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "GÖRKEM DÖRTKÖŞE",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2802",
        "Personel": "İSMAİL GEZGİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2776",
        "Personel": "SELİM ÖZKAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "İdari İşler Şoför  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "GÖKHAN SUBAŞI",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2928",
        "Personel": "EBRU GÜNEŞ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Tasarım",
        "Görev": "Kalıp Tasarım Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "KAAN KARACA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2884",
        "Personel": "AYHAN TOSUN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "HIDIR BESKİ",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2800",
        "Personel": "İSMAİL DEĞİRMENCİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "3044",
        "Personel": "METİN ÇILGIN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama Kalite Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2889",
        "Personel": "VELİ KAZANKAYA",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Bakım ve Enerji",
        "Bölüm": "Mekanik",
        "Görev": "Mekanik Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "FURKAN ÖZNAM",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2791",
        "Personel": "AHMET BULUT",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Kalite Ayrım",
        "Görev": "Taşlama  Kalite Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "ERHAN ÇAKIR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2804",
        "Personel": "YAĞIZ ÖZKAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "CNC",
        "Görev": "CNC Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "HAKAN OKTAY",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2512",
        "Personel": "İZZET ÖNER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2148",
        "Personel": "AYŞE CAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2149",
        "Personel": "AYŞE GÜNDÜZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2233",
        "Personel": "FİRDES YILMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2169",
        "Personel": "BEYZANUR KAYASAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Kalite Güvence Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2288",
        "Personel": "KEREM ATBAŞ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2441",
        "Personel": "LEYLA ÖZYİĞİT",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Son Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2483",
        "Personel": "RIFAT IŞIK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2554",
        "Personel": "HÜSEYİN MURAT TAŞDELEN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "CNC",
        "Görev": "Torna Operatör NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "HAKAN OKTAY",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2215",
        "Personel": "BETÜL BOZDEMİR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Lojistik Destek",
        "Görev": "Lojistik Destek Sistem Operatör NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "YALÇIN DURSUN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2408",
        "Personel": "SEMİH ÖZBİÇER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2021",
        "Personel": "ERDOĞAN ÇELİK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2626",
        "Personel": "HAMDİ MUTLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1822",
        "Personel": "RECEP TURHAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1483",
        "Personel": "FATMA ÇÖMEZ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1578",
        "Personel": "MERVE ERYILMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme Sistem Sorumlusu NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "CEREN DEMİR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1824",
        "Personel": "YUNUS SAPAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1285",
        "Personel": "ŞEYMA KESKİNOĞLU",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1117",
        "Personel": "ÖZGE ÇALIŞKAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1111",
        "Personel": "HEDİYE YABAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dijital",
        "Görev": "Dijital  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "MECİT ERTEKİN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1472",
        "Personel": "AHMET ÇALI",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalıp Tasarım",
        "Bölüm": "Kalıp Üretimi",
        "Görev": "Alçı Kalıp İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "İSMAİL MURAT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1696",
        "Personel": "FATMA GÜNAYDIN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "ÖZGE SÜRGİT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1616",
        "Personel": "VOLKAN ARSIN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1490",
        "Personel": "ERDİNÇ ŞEN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Stok Kontrol Uzman NW",
        "Organizasyon yeri": "UZMN",
        "Yönetici": "ALPER ATAY",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1741",
        "Personel": "DUYGU YILMAZ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CEREN DEMİR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1306",
        "Personel": "NURULLAH SUBAŞI",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "Proses Kontrol",
        "Görev": "Proses Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1734",
        "Personel": "NEŞE IŞIK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "CEREN DEMİR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1402",
        "Personel": "ADEM KALKAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Depo Sevkiyat Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1211",
        "Personel": "FERDİ KINIK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0833",
        "Personel": "İSMAİL BARUT",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1091",
        "Personel": "NİHAT EFE",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Son Kontrol Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "İNCİ PINAR",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0755",
        "Personel": "HATİCE KUYUCU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Paketleme",
        "Görev": "Paketleme Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "HIDIR BESKİ",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0992",
        "Personel": "ÖZGE TAŞKIRAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Metot/Opex",
        "Bölüm": "Metot",
        "Görev": "Metot Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "GÖRKEM DÖRTKÖŞE",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0988",
        "Personel": "MERAL KÖKSAL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "ÖZGE SÜRGİT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0420",
        "Personel": "AHMET AKSU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "İnsan Kaynakları ve İdari İşler",
        "Birim": "İdari İşler",
        "Bölüm": "İdari İşler",
        "Görev": "İdari İşler Şoför  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "RIDVAN ÖZKAN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0425",
        "Personel": "ÇETİN DAYAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama Arıtma İşçi NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0174",
        "Personel": "HANİFİ ÇAKMAK",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0009",
        "Personel": "ABDURRAHMAN ERKUŞ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0164",
        "Personel": "GÜLCAN MURATHANOĞULLARI",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0052",
        "Personel": "AYŞE PATIR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0262",
        "Personel": "SEVDA HIDIRLAR",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0015",
        "Personel": "AKTÜRK TAPARİ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0153",
        "Personel": "FATMA KARATAŞ",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Dekor",
        "Görev": "Dekor İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SENEM TUĞRUL ÇETİNKAYA",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0203",
        "Personel": "MEHMET ŞERİF CAMAN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0220",
        "Personel": "MUSTAFA DEMİRAY",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "PELİN AKIN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2594",
        "Personel": "ERKAN GÜNDOĞDU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlı Fırın Yükleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2231",
        "Personel": "KENAN DEĞİRMENCİ",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Fırınlar",
        "Görev": "Bisküvi Stok İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "HALİL ERHAN KILIÇ",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2551",
        "Personel": "ONAY BİNGÖL",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2160",
        "Personel": "İMREN METİN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "ArGe&amp;Proses",
        "Bölüm": "ArGe",
        "Görev": "ArGe Tekniker  NW",
        "Organizasyon yeri": "TKNR",
        "Yönetici": "ÖZGE SÜRGİT",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "1104",
        "Personel": "ZELİHA GÜVEN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlı Fırın Yükleme İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0515",
        "Personel": "MEHMET ER",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Hammadde Hazırlama",
        "Bölüm": "Hammadde Hazırlama",
        "Görev": "Hammadde Hazırlama  İşçi  NW",
        "Organizasyon yeri": "ISCI",
        "Yönetici": "ÖMER FARUK TABAK",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "0435",
        "Personel": "İBRAHİM KALYONCU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2819",
        "Personel": "ALİ ÇAKMAK",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Fırınlar",
        "Görev": "Bisküvi Pişirim Araba Bakım  Takım Lideri  NW",
        "Organizasyon yeri": "TKL",
        "Yönetici": "HALİL ERHAN KILIÇ",
        "newScala": "4",
        "newScore": "81"
    },
    {
        "Sicil No": "2458",
        "Personel": "HAYRUNNİSA AKIN",
        "Çalışma Yeri": "Çayırova",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Teknik İşler",
        "Birim": "Kalite Güvence",
        "Bölüm": "Kalite Güvence",
        "Görev": "Son Kontrol Teknisyen  NW",
        "Organizasyon yeri": "TKNS",
        "Yönetici": "BURHAN GÖL",
        "newScala": "5",
        "newScore": "91"
    },
    {
        "Sicil No": "0758",
        "Personel": "NESLİHAN ULU",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Tedarik Zinciri",
        "Birim": "Lojistik",
        "Bölüm": "Depo Sevkiyat",
        "Görev": "Koli Depo Operatör  NW",
        "Organizasyon yeri": "OPR",
        "Yönetici": "FAHRİ AYKUT ERDAL",
        "newScala": "5",
        "newScore": "91"
    },
    {
        "Sicil No": "0434",
        "Personel": "HARUN ÜNALAN",
        "Çalışma Yeri": "Pazaryeri",
        "Grubu": "Mavi Yaka",
        "Üst Birim": "Fabrikalar Direktörlüğü",
        "Birim": "Üretim",
        "Bölüm": "Sırlama",
        "Görev": "Sırlama Vardiya Lideri  NW",
        "Organizasyon yeri": "VRDL",
        "Yönetici": "SAMET TÜRKAN",
        "newScala": "5",
        "newScore": "91"
    }
]
