# FROM node
FROM node:20.9.0-alpine3.18

WORKDIR /v2_my

COPY . .

RUN npm i -g pnpm
RUN pnpm i

CMD ["npm", "start"]
EXPOSE 5173

# --------------------------------
# $ cd /v2_my
# $ docker build -t myperformans .
# $ docker run -p 5173:5173 --name myperformans myperformans
# $ docker run -d -p 5173:5173 --name myperformans myperformans
# $ docker run -d -p 80:5173 --name myperformans bonnadijital/myperformans
# Browser: http://localhost:5173