# Base image
FROM node:latest

# Çalışma dizini oluşturma
WORKDIR /v2_by

# Bağımlılıkları kopyalama ve yükleme
COPY package.json yarn.lock ./

# Uygulama dosyalarını kopyalama
COPY . .

# Uygulamayı başlatma
CMD ["yarn", "start"]